#!/usr/bin/env bun
// 体积对比报告生成 —— 打包 beautiful-mermaid 并测量本项目 build 产物的 raw/gzip 字节
import { gzipSync } from "node:zlib";
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";

const ROOT = import.meta.dirname + "/..",
  REF_DIR = ROOT + "/references/beautiful-mermaid",
  DEMO_DIST = ROOT + "/demo/dist",
  REPORT_DIR = ROOT + "/workflow/reports",
  DEMO_CONST = ROOT + "/demo/const";

// 测量文件原始字节和 gzip 字节
const measureFile = (file_path) => {
  const raw = readFileSync(file_path),
    gzip = gzipSync(raw);
  return [raw.length, gzip.length];
};

// 获取 references 仓库的 git commit 和 describe
const gitInfo = (dir) => {
  const commit = execSync("git rev-parse HEAD", { cwd: dir, encoding: "utf8" }).trim(),
    describe = execSync("git describe --tags", { cwd: dir, encoding: "utf8" }).trim();
  return [commit, describe];
};

// 从 index.html 解析入口脚本 src 路径 (/assets/index-HASH.js)
const parseEntry = (html_path) => {
  const html = readFileSync(html_path, "utf8"),
    m = html.match(/<script[^>]+src="(\/assets\/index-[^"]+\.js)"/);
  if (!m) throw new Error("entry script not found in " + html_path);
  return m[1];
};

// 用 bun build 打包 beautiful-mermaid (externals 对齐 tsup.config.ts)
const bundleBm = () => {
  const entry = REF_DIR + "/src/index.ts",
    out = tmpdir() + "/beautiful-mermaid-bundle.js";
  execSync(
    'bun build "' + entry + '" --external elkjs --external entities --outfile "' + out + '"',
    { cwd: REF_DIR, stdio: "pipe" },
  );
  return out;
};

const buildBmReport = () => {
  const [commit, describe] = gitInfo(REF_DIR),
    version = JSON.parse(readFileSync(REF_DIR + "/package.json", "utf8")).version,
    [raw_bytes, gzip_bytes] = measureFile(bundleBm());
  return {
    source: {
      repo: "lukilabs/beautiful-mermaid",
      url: "https://github.com/lukilabs/beautiful-mermaid",
      localPath: "references/beautiful-mermaid",
      commit,
      gitDescribe: describe,
      version,
      bundleMethod: "bun build with externals [elkjs, entities] matching tsup.config.ts",
    },
    rawBytes: raw_bytes,
    gzipBytes: gzip_bytes,
  };
};

const buildOursReport = () => {
  const entry_src = parseEntry(DEMO_DIST + "/index.html"),
    [raw_bytes, gzip_bytes] = measureFile(DEMO_DIST + entry_src);
  return {
    entry: "demo/dist" + entry_src,
    rawBytes: raw_bytes,
    gzipBytes: gzip_bytes,
  };
};

mkdirSync(REPORT_DIR, { recursive: true });

const bm_report = buildBmReport(),
  ours_report = buildOursReport(),
  report = {
    generatedAt: new Date().toISOString(),
    loop: "size-loop",
    beautifulMermaid: bm_report,
    ours: ours_report,
    verification: {
      beautifulMermaidBundledFromLocal: true,
      ourEntryFromRealBuild: true,
    },
  };

writeFileSync(REPORT_DIR + "/size-report.json", JSON.stringify(report, null, 2) + "\n");

const size_data =
  "// Auto-generated by sh/size-report.js — do not edit manually\n" +
  "// Size comparison data (performance proxy, not a runtime benchmark)\n\n" +
  "export const SIZE_DATA = {\n" +
  "  beautifulMermaid: {\n" +
  '    label: "beautiful-mermaid",\n' +
  '    version: "' +
  bm_report.source.version +
  '",\n' +
  "    rawBytes: " +
  bm_report.rawBytes +
  ",\n" +
  "    gzipBytes: " +
  bm_report.gzipBytes +
  ",\n" +
  "  },\n" +
  "  ours: {\n" +
  '    label: "mermaid2svg",\n' +
  "    rawBytes: " +
  ours_report.rawBytes +
  ",\n" +
  "    gzipBytes: " +
  ours_report.gzipBytes +
  ",\n" +
  "  },\n" +
  "};\n";

writeFileSync(DEMO_CONST + "/sizeData.js", size_data);

console.log("size-report.json -> workflow/reports/");
console.log(
  "  beautiful-mermaid " + bm_report.source.version + " (" + bm_report.source.gitDescribe + ")",
);
console.log("    raw:  " + bm_report.rawBytes + " bytes");
console.log("    gzip: " + bm_report.gzipBytes + " bytes");
console.log("  ours (" + ours_report.entry + ")");
console.log("    raw:  " + ours_report.rawBytes + " bytes");
console.log("    gzip: " + ours_report.gzipBytes + " bytes");
