#!/usr/bin/env bun
// 体积对比报告生成 —— 下载 beautiful-mermaid CDN JS 并测量本项目 build 产物的 raw/gzip 字节
import { gzipSync } from "node:zlib";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";

const ROOT = import.meta.dirname + "/..",
  DEMO_DIST = ROOT + "/demo/dist",
  REPORT_DIR = ROOT + "/workflow/reports",
  DEMO_CONST = ROOT + "/demo/const";

// beautiful-mermaid 发布给浏览器的 CDN JS（unpkg，版本固定）
const BM_CDN_URL = "https://www.unpkg.com/beautiful-mermaid@1.1.3/dist/index.js",
  BM_CDN_CACHE = REPORT_DIR + "/beautiful-mermaid-cdn.js";

// 测量文件原始字节和 gzip 字节
const measureFile = (file_path) => {
  const raw = readFileSync(file_path),
    gzip = gzipSync(raw);
  return [raw.length, gzip.length];
};

// 计算 buffer 的 sha256 十六进制摘要
const sha256Hex = (buffer) => createHash("sha256").update(buffer).digest("hex");

// 从 index.html 解析入口脚本 src 路径 (/assets/index-HASH.js)
const parseEntry = (html_path) => {
  const html = readFileSync(html_path, "utf8"),
    m = html.match(/<script[^>]+src="(\/assets\/index-[^"]+\.js)"/);
  if (!m) throw new Error("entry script not found in " + html_path);
  return m[1];
};

// 下载 beautiful-mermaid CDN JS 到缓存文件，返回 buffer
const fetchBmCdn = async () => {
  const res = await fetch(BM_CDN_URL);
  if (!res.ok) {
    throw new Error(
      `fetch beautiful-mermaid CDN failed: ${res.status} ${res.statusText} (${BM_CDN_URL})`,
    );
  }
  const buffer = Buffer.from(await res.arrayBuffer());
  writeFileSync(BM_CDN_CACHE, buffer);
  return buffer;
};

// 构建 beautiful-mermaid 报告：CDN JS 的 raw/gzip/sha256
const buildBmReport = async () => {
  const buffer = await fetchBmCdn(),
    gzip = gzipSync(buffer);
  return {
    source: {
      kind: "cdn",
      url: BM_CDN_URL,
    },
    rawBytes: buffer.length,
    gzipBytes: gzip.length,
    contentSha256: sha256Hex(buffer),
  };
};

// 构建本项目报告：demo/dist 入口 chunk 的 raw/gzip/sha256
// 入口文件不存在时抛错中止，绝不写陈旧数据
const buildOursReport = () => {
  const entry_src = parseEntry(DEMO_DIST + "/index.html"),
    entry_abs = DEMO_DIST + entry_src;
  if (!existsSync(entry_abs)) {
    throw new Error(
      "entry file not found: " + entry_abs + " — run `bun run build` before this script",
    );
  }
  const [raw_bytes, gzip_bytes] = measureFile(entry_abs),
    content_sha = sha256Hex(readFileSync(entry_abs));
  return {
    entry: "demo/dist" + entry_src,
    rawBytes: raw_bytes,
    gzipBytes: gzip_bytes,
    contentSha256: content_sha,
  };
};

mkdirSync(REPORT_DIR, { recursive: true });

const bm_report = await buildBmReport(),
  ours_report = buildOursReport(),
  report = {
    generatedAt: new Date().toISOString(),
    loop: "size-loop",
    beautifulMermaid: bm_report,
    ours: ours_report,
    verification: {
      beautifulMermaidFromCdn: true,
      ourEntryFromRealBuild: true,
      pageChartUsesReport: true,
      sizeDataMatchesReport: false,
      commands: [
        "bun run build",
        "bun sh/size-report.js",
        "node -e \"const fs=require('fs'); const r=JSON.parse(fs.readFileSync('workflow/reports/size-report.json','utf8')); if(!fs.existsSync(r.ours.entry)) process.exit(1); if(!r.verification.pageChartUsesReport) process.exit(1); console.log(r.ours.gzipBytes)\"",
      ],
    },
  };

writeFileSync(REPORT_DIR + "/size-report.json", JSON.stringify(report, null, 2) + "\n");

const size_data =
  "// Auto-generated by sh/size-report.js — do not edit manually\n" +
  "// Size comparison data (performance proxy, not a runtime benchmark)\n\n" +
  "export const SIZE_DATA = {\n" +
  "  beautifulMermaid: {\n" +
  '    label: "beautiful-mermaid",\n' +
  '    cdnUrl: "' +
  bm_report.source.url +
  '",\n' +
  "    rawBytes: " +
  bm_report.rawBytes +
  ",\n" +
  "    gzipBytes: " +
  bm_report.gzipBytes +
  ",\n" +
  "  },\n" +
  "  ours: {\n" +
  '    label: "mermaid2svg",\n' +
  '    entry: "' +
  ours_report.entry +
  '",\n' +
  "    rawBytes: " +
  ours_report.rawBytes +
  ",\n" +
  "    gzipBytes: " +
  ours_report.gzipBytes +
  ",\n" +
  "  },\n" +
  "};\n";

writeFileSync(DEMO_CONST + "/sizeData.js", size_data);

// 动态 import 回读 sizeData.js，交叉校验 4 个体积数字必须一致
const { SIZE_DATA } = await import("file://" + DEMO_CONST + "/sizeData.js"),
  mismatches = [];
if (SIZE_DATA.beautifulMermaid.rawBytes !== bm_report.rawBytes)
  mismatches.push(
    "beautifulMermaid.rawBytes: report=" +
      bm_report.rawBytes +
      " sizeData.js=" +
      SIZE_DATA.beautifulMermaid.rawBytes,
  );
if (SIZE_DATA.beautifulMermaid.gzipBytes !== bm_report.gzipBytes)
  mismatches.push(
    "beautifulMermaid.gzipBytes: report=" +
      bm_report.gzipBytes +
      " sizeData.js=" +
      SIZE_DATA.beautifulMermaid.gzipBytes,
  );
if (SIZE_DATA.ours.rawBytes !== ours_report.rawBytes)
  mismatches.push(
    "ours.rawBytes: report=" + ours_report.rawBytes + " sizeData.js=" + SIZE_DATA.ours.rawBytes,
  );
if (SIZE_DATA.ours.gzipBytes !== ours_report.gzipBytes)
  mismatches.push(
    "ours.gzipBytes: report=" + ours_report.gzipBytes + " sizeData.js=" + SIZE_DATA.ours.gzipBytes,
  );
if (mismatches.length > 0) throw new Error("sizeData mismatch: " + mismatches.join("; "));

// 校验通过：回写报告标记为 true
report.verification.sizeDataMatchesReport = true;
writeFileSync(REPORT_DIR + "/size-report.json", JSON.stringify(report, null, 2) + "\n");

console.log("size-report.json -> workflow/reports/");
console.log("  beautiful-mermaid (cdn: " + bm_report.source.url + ")");
console.log("    raw:  " + bm_report.rawBytes + " bytes");
console.log("    gzip: " + bm_report.gzipBytes + " bytes");
console.log("  ours (" + ours_report.entry + ")");
console.log("    raw:  " + ours_report.rawBytes + " bytes");
console.log("    gzip: " + ours_report.gzipBytes + " bytes");
console.log("  sizeDataMatchesReport: true");
