export default {
  start: "Start",
  process: "Process",
  end: "End",
  alice: "Alice",
  bob: "Bob",
  hello: "Hello",
  hi: "Hi",
  animal: "Animal",
  name: "name",
  age: "age",
  eat: "eat()",
  sleep: "sleep()",
  idle: "Idle",
  running: "Running",
  start_action: "start",
  stop_action: "stop",
  customer: "CUSTOMER",
  order: "ORDER",
  places: "places",
  pets: "Pets",
  dogs: "Dogs",
  cats: "Cats",
  gantt_title: "Adding GANTT diagram to mermaid",
  section_a: "A section",
  completed_task: "Completed task",
  active_task: "Active task",
  product_sales: "Product Sales",
  widgets: "Widgets",
  gadgets: "Gadgets",
  gizmos: "Gizmos",
  doodads: "Doodads",
  thingamajigs: "Thingamajigs",
  applicant: "Applicant",
  submit_order: "Submit Order",
  manager_approval: "Manager Approval",
  approver: "Approver",
  approve: "Approve",
  approved: "Approved",
  reject: "Reject",
  returned_for_revision: "Returned for Revision",
  system: "System",
  generate_order: "Generate Order",
  commit_code: "Commit Code",
  push_branch: "Push Branch",
  lint_check: "Lint Check",
  unit_test: "Unit Test",
  build_image: "Build Image",
  deploy_staging: "Deploy to Staging",
  acceptance_test: "Acceptance Test",
  deploy_production: "Deploy to Production",
  rollback: "Rollback",
  monitor_alert: "Monitor & Alert",
  dev: "Dev",
  ci: "CI",
  cd: "CD",
  monitor: "Monitor",
  client: "Client",
  server: "Server",
  http_request_retry: "HTTP Request Retry",
  max_3_retries: "Max 3 Retries",
  get_api_data: "GET /api/data",
  retry_success: "Success",
  ok_200: "200 OK",
  retry_failure: "Failure",
  error_500: "500 Error",
  wait_1s_retry: "Wait 1s then Retry",
  all_failed: "All Failed",
  trigger_degraded: "Trigger Degraded",
  user: "User",
  client_actor: "Client",
  auth_server: "AuthServer",
  resource_server: "ResourceServer",
  authorization_phase: "1. Authorization Phase",
  click_login: "Click Login",
  redirect_auth: "Redirect to Auth Page",
  show_login: "Show Login Page",
  enter_credentials: "Enter Credentials",
  return_auth_code: "Return Auth Code",
  exchange_token: "2. Exchange Token",
  code_secret: "code + client_secret",
  access_token: "access_token",
  request_resource: "Request Resource + access_token",
  return_user_data: "Return User Data",
  dog: "Dog",
  cat: "Cat",
  bird: "Bird",
  breed: "breed",
  bark: "bark()",
  indoor: "indoor",
  meow: "meow()",
  wingspan: "wingspan",
  fly: "fly()",
  strategy: "Strategy",
  execute_int: "execute(int, int) int",
  context: "Context",
  set_strategy: "setStrategy(Strategy) void",
  execute_strategy: "executeStrategy(int, int) int",
  add_strategy: "AddStrategy",
  sub_strategy: "SubStrategy",
  mul_strategy: "MulStrategy",
  logger_factory: "LoggerFactory",
  log_string: "log(String) void",
  strategy_note: "Strategy Interface: Define Algorithms",
  context_note: "Context: Holds Strategy Reference",
  composite: "Composite",
  dependency: "Dependency",
  pending_payment: "Pending Payment",
  user_pays: "User Pays",
  paid: "Paid",
  cancelled: "Cancelled",
  timeout_or_cancel: "Timeout or User Cancel",
  pending_shipping: "Pending Shipping",
  merchant_ships: "Merchant Ships",
  shipped: "Shipped",
  received: "Received",
  user_confirms_receipt: "User Confirms Receipt",
  completed: "Completed",
  auto_confirm_7d: "Auto Confirms in 7 Days",
  auto_cancel_30min: "Auto Cancel in 30 Mins if Unpaid",
  receive_instruction: "Receive Instruction",
  button_pressed: "Button Pressed",
  fork_state: "fork_state",
  up: "Up",
  target_floor_up: "Target Floor is Up",
  down: "Down",
  target_floor_down: "Target Floor is Down",
  arrive: "Arrive",
  target: "Target",
  door_opens: "Door Opens",
  door_holds: "Door Holds",
  door_closes: "Door Closes",
  after_5s: "After 5 Seconds",
  join_state: "join_state",
  alarm: "Alarm",
  emergency_button: "Emergency Button",
  elevator_history: "History State: Elevator remembers last direction",
  order_item: "ORDER_ITEM",
  product: "PRODUCT",
  category: "CATEGORY",
  contains: "contains",
  refers_to: "refers_to",
  belongs_to: "belongs_to",
  id: "id",
  email: "email",
  customer_id: "customer_id",
  created_at: "created_at",
  order_id: "order_id",
  product_id: "product_id",
  quantity: "quantity",
  price: "price",
  account: "ACCOUNT",
  transaction: "TRANSACTION",
  card: "CARD",
  loan: "LOAN",
  owns: "owns",
  has: "has",
  linked_to: "linked_to",
  secures: "secures",
  account_no: "account_no",
  balance: "balance",
  currency: "currency",
  opened_at: "opened_at",
  from_account: "from_account",
  to_account: "to_account",
  amount: "amount",
  trans_at: "trans_at",
  card_no: "card_no",
  expire_date: "expire_date",
  card_type: "card_type",
  principal: "principal",
  rate: "rate",
  term_months: "term_months",
  id_card: "id_card",
  phone: "phone",
  device_traffic_2024: "Device Traffic Distribution 2024",
  mobile: "Mobile",
  desktop: "Desktop",
  tablet: "Tablet",
  other: "Other",
  browser_market_2024: "Global Browser Market Share 2024 Q4 (StatCounter)",
  chrome: "Chrome",
  safari: "Safari",
  edge: "Edge",
  firefox: "Firefox",
  samsung_internet: "Samsung Internet",
  others: "Other",
  software_project_gantt: "Software Development Project Gantt",
  requirements: "Requirements",
  requirement_analysis: "Requirement Analysis",
  requirement_review: "Requirement Review",
  design: "Design",
  ui_design: "UI Design",
  architecture_design: "Architecture Design",
  development: "Development",
  frontend_dev: "Frontend Dev",
  backend_dev: "Backend Dev",
  integration_testing: "Integration Testing",
  testing: "Testing",
  go_live: "Go-Live",
  cross_quarter_2024: "2024 Q1-Q2 Cross-Quarter Project",
  q1: "Q1",
  project_initiation: "Project Initiation",
  research: "Research",
  prototype_dev: "Prototype Dev",
  internal_test: "Internal Test",
  q2: "Q2",
  public_beta: "Public Beta",
  bug_fix: "Bug Fix",
  official_release: "Official Release",
  operation_promotion: "Operation & Promotion",
  quarterly_sales_comparison: "Quarterly Sales Comparison of Three Products",
  sales_10k: "Sales (10k units)",
  quarterly_revenue_comparison: "Quarterly Revenue Comparison 2023 vs 2024",
  revenue_million_usd: "Revenue (Million USD)",
};
