// Auto-generated by sh/size-report.js — do not edit manually
// Size comparison data (performance proxy, not a runtime benchmark)

export const SIZE_DATA = {
  beautifulMermaid: {
    label: "beautiful-mermaid",
    version: "1.1.3",
    rawBytes: 328094,
    gzipBytes: 66816,
  },
  ours: {
    label: "mermaid2svg",
    rawBytes: 124434,
    gzipBytes: 40584,
  },
};
