// Auto-generated by sh/size-report.js — do not edit manually
// Size comparison data (performance proxy, not a runtime benchmark)

export const SIZE_DATA = {
  beautifulMermaid: {
    label: "beautiful-mermaid",
    cdnUrl: "https://www.unpkg.com/beautiful-mermaid@1.1.3/dist/index.js",
    rawBytes: 335537,
    gzipBytes: 68977,
  },
  ours: {
    label: "mermaid2svg",
    entry: "demo/dist/assets/index-jBzPFP_h.js",
    rawBytes: 218660,
    gzipBytes: 70550,
  },
};
